server {
    listen 80;

    # All requests to the root URL are proxied to the front-end service
    location / {
        proxy_pass http://front-end:9000;
    }
    # Requests to /api are proxied to the back-end service
    location /api {
        proxy_pass http://back-end:5252;
    }
}