# Use the official Ubuntu base image
FROM ubuntu:latest

# Update the package list and install necessary packages
RUN apt-get update && apt-get upgrade -y

# When the container starts, execute the echo command
CMD echo "Hello, World"